package enums

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestBizCodeEnum_CodeAndMessage(t *testing.T) {
	tests := []struct {
		name         string
		enum         BizCodeEnum
		expectedCode int
		expectedMsg  string
	}{
		// Common
		{"COMMON_REPEAT_OPERATION", COMMON_REPEAT_OPERATION, 110001, "重复操作，请稍后再试"},
		{"COMMON_NETWORK_ERROR", COMMON_NETWORK_ERROR, 110002, "网络异常"},

		// Link Group
		{"GROUP_REPEAT", GROUP_REPEAT, 230001, "组名已经存在"},
		{"GROUP_NOT_EXIST", GROUP_NOT_EXIST, 230002, "组名不存在"},
		{"GROUP_ADD_FAIL", GROUP_ADD_FAIL, 230003, "新增组失败"},
		{"GROUP_OPERATE_FAIL", GROUP_OPERATE_FAIL, 230004, "操作组失败"},

		// Verification Code
		{"CODE_GENERATE_ERROR", CODE_GENERATE_ERROR, 240001, "验证码生成失败"},
		{"CODE_LIMITED", CODE_LIMITED, 240002, "验证码发送过快，请稍后再试"},
		{"CODE_ERROR", CODE_ERROR, 240003, "验证码错误"},
		{"CAPTCHA_ERROR", CAPTCHA_ERROR, 240004, "图形验证码错误"},

		// Account
		{"ACCOUNT_REPEAT", ACCOUNT_REPEAT, 250001, "账号已经存在"},
		{"ACCOUNT_NOT_EXIST", ACCOUNT_NOT_EXIST, 250002, "账号不存在"},
		{"ACCOUNT_PWD_ERROR", ACCOUNT_PWD_ERROR, 250003, "账号密码错误"},
		{"ACCOUNT_UNLOGIN", ACCOUNT_UNLOGIN, 250004, "账号未登录"},
		{"ACCOUNT_TOKEN_ERROR", ACCOUNT_TOKEN_ERROR, 250005, "token不合法"},

		// Short Link
		{"SHORT_LINK_NOT_EXIST", SHORT_LINK_NOT_EXIST, 260001, "短链不存在"},

		// Order
		{"ORDER_PRICE_FAIL", ORDER_PRICE_FAIL, 280001, "价格不合法"},
		{"ORDER_REPEAT_SUBMIT", ORDER_REPEAT_SUBMIT, 280002, "请勿重复提交"},
		{"ORDER_TOKEN_MISSING", ORDER_TOKEN_MISSING, 280003, "token不存在，请重新获取"},
		{"ORDER_NOT_EXIST", ORDER_NOT_EXIST, 280004, "订单不存在"},
		{"ORDER_STATE_ERROR", ORDER_STATE_ERROR, 280005, "订单状态异常"},
		{"ORDER_CANCEL_SUCCESS", ORDER_CANCEL_SUCCESS, 280006, "订单取消成功"},
		{"ORDER_CONFIRM_SUCCESS", ORDER_CONFIRM_SUCCESS, 280007, "订单确认成功"},

		// Payment
		{"PAY_ORDER_FAIL", PAY_ORDER_FAIL, 300001, "创建支付订单失败"},
		{"PAY_CALLBACK_SIGN_FAIL", PAY_CALLBACK_SIGN_FAIL, 300002, "回调签名验证失败"},
		{"PAY_ORDER_STATE_ERROR", PAY_ORDER_STATE_ERROR, 300003, "订单状态异常"},
		{"PAY_ORDER_TIMEOUT_ERROR", PAY_ORDER_TIMEOUT_ERROR, 300004, "订单超时"},

		// Data
		{"DATA_OUT_OF_LIMIT_SIZE", DATA_OUT_OF_LIMIT_SIZE, 400001, "数据量超过限制"},
		{"DATA_OUT_OF_LIMIT_DATE", DATA_OUT_OF_LIMIT_DATE, 400002, "日期范围超过限制"},

		// Flow Control
		{"CONTROL_FLOW", CONTROL_FLOW, 500101, "限流控制"},
		{"CONTROL_DEGRADE", CONTROL_DEGRADE, 500201, "降级控制"},
		{"CONTROL_AUTH", CONTROL_AUTH, 500301, "认证控制"},

		// Traffic
		{"TRAFFIC_NOT_EXIST", TRAFFIC_NOT_EXIST, 600001, "流量包不存在"},
		{"TRAFFIC_REDUCE_FAIL", TRAFFIC_REDUCE_FAIL, 600002, "流量包扣减失败"},
		{"TRAFFIC_DATA_ERROR", TRAFFIC_DATA_ERROR, 600003, "数据异常"},

		// File Upload
		{"FILE_UPLOAD_ERROR", FILE_UPLOAD_ERROR, 700001, "文件上传失败"},

		// DB Routing
		{"DB_ROUTING_ERROR", DB_ROUTING_ERROR, 800001, "数据库路由错误"},

		// MQ
		{"MQ_CONSUME_ERROR", MQ_CONSUME_ERROR, 900001, "消息消费异常"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.expectedCode, tt.enum.Code(),
				"%s 的 Code() 应为 %d", tt.name, tt.expectedCode)
			assert.Equal(t, tt.expectedMsg, tt.enum.Message(),
				"%s 的 Message() 应为 %q", tt.name, tt.expectedMsg)
		})
	}
}

func TestBizCodeEnum_CodesUnique(t *testing.T) {
	allEnums := []BizCodeEnum{
		COMMON_REPEAT_OPERATION, COMMON_NETWORK_ERROR,
		GROUP_REPEAT, GROUP_NOT_EXIST, GROUP_ADD_FAIL, GROUP_OPERATE_FAIL,
		CODE_GENERATE_ERROR, CODE_LIMITED, CODE_ERROR, CAPTCHA_ERROR,
		ACCOUNT_REPEAT, ACCOUNT_NOT_EXIST, ACCOUNT_PWD_ERROR, ACCOUNT_UNLOGIN, ACCOUNT_TOKEN_ERROR,
		SHORT_LINK_NOT_EXIST,
		ORDER_PRICE_FAIL, ORDER_REPEAT_SUBMIT, ORDER_TOKEN_MISSING, ORDER_NOT_EXIST,
		ORDER_STATE_ERROR, ORDER_CANCEL_SUCCESS, ORDER_CONFIRM_SUCCESS,
		PAY_ORDER_FAIL, PAY_CALLBACK_SIGN_FAIL, PAY_ORDER_STATE_ERROR, PAY_ORDER_TIMEOUT_ERROR,
		DATA_OUT_OF_LIMIT_SIZE, DATA_OUT_OF_LIMIT_DATE,
		CONTROL_FLOW, CONTROL_DEGRADE, CONTROL_AUTH,
		TRAFFIC_NOT_EXIST, TRAFFIC_REDUCE_FAIL, TRAFFIC_DATA_ERROR,
		FILE_UPLOAD_ERROR,
		DB_ROUTING_ERROR,
		MQ_CONSUME_ERROR,
	}

	seen := make(map[int]string)
	for _, e := range allEnums {
		if prev, exists := seen[e.Code()]; exists {
			t.Errorf("错误码 %d 重复，出现在 %s 和 %s", e.Code(), prev, e.Message())
		}
		seen[e.Code()] = e.Message()
	}
}

func TestBizCodeEnum_AllCodesPositive(t *testing.T) {
	allEnums := []BizCodeEnum{
		COMMON_REPEAT_OPERATION, COMMON_NETWORK_ERROR,
		GROUP_REPEAT, GROUP_NOT_EXIST, GROUP_ADD_FAIL, GROUP_OPERATE_FAIL,
		CODE_GENERATE_ERROR, CODE_LIMITED, CODE_ERROR, CAPTCHA_ERROR,
		ACCOUNT_REPEAT, ACCOUNT_NOT_EXIST, ACCOUNT_PWD_ERROR, ACCOUNT_UNLOGIN, ACCOUNT_TOKEN_ERROR,
		SHORT_LINK_NOT_EXIST,
		ORDER_PRICE_FAIL, ORDER_REPEAT_SUBMIT, ORDER_TOKEN_MISSING, ORDER_NOT_EXIST,
		ORDER_STATE_ERROR, ORDER_CANCEL_SUCCESS, ORDER_CONFIRM_SUCCESS,
		PAY_ORDER_FAIL, PAY_CALLBACK_SIGN_FAIL, PAY_ORDER_STATE_ERROR, PAY_ORDER_TIMEOUT_ERROR,
		DATA_OUT_OF_LIMIT_SIZE, DATA_OUT_OF_LIMIT_DATE,
		CONTROL_FLOW, CONTROL_DEGRADE, CONTROL_AUTH,
		TRAFFIC_NOT_EXIST, TRAFFIC_REDUCE_FAIL, TRAFFIC_DATA_ERROR,
		FILE_UPLOAD_ERROR,
		DB_ROUTING_ERROR,
		MQ_CONSUME_ERROR,
	}

	for _, e := range allEnums {
		assert.Greater(t, e.Code(), 0, "错误码应为正数，实际: %d (%s)", e.Code(), e.Message())
	}
}

func TestBizCodeEnum_AllMessagesNonEmpty(t *testing.T) {
	allEnums := []BizCodeEnum{
		COMMON_REPEAT_OPERATION, COMMON_NETWORK_ERROR,
		GROUP_REPEAT, GROUP_NOT_EXIST, GROUP_ADD_FAIL, GROUP_OPERATE_FAIL,
		CODE_GENERATE_ERROR, CODE_LIMITED, CODE_ERROR, CAPTCHA_ERROR,
		ACCOUNT_REPEAT, ACCOUNT_NOT_EXIST, ACCOUNT_PWD_ERROR, ACCOUNT_UNLOGIN, ACCOUNT_TOKEN_ERROR,
		SHORT_LINK_NOT_EXIST,
		ORDER_PRICE_FAIL, ORDER_REPEAT_SUBMIT, ORDER_TOKEN_MISSING, ORDER_NOT_EXIST,
		ORDER_STATE_ERROR, ORDER_CANCEL_SUCCESS, ORDER_CONFIRM_SUCCESS,
		PAY_ORDER_FAIL, PAY_CALLBACK_SIGN_FAIL, PAY_ORDER_STATE_ERROR, PAY_ORDER_TIMEOUT_ERROR,
		DATA_OUT_OF_LIMIT_SIZE, DATA_OUT_OF_LIMIT_DATE,
		CONTROL_FLOW, CONTROL_DEGRADE, CONTROL_AUTH,
		TRAFFIC_NOT_EXIST, TRAFFIC_REDUCE_FAIL, TRAFFIC_DATA_ERROR,
		FILE_UPLOAD_ERROR,
		DB_ROUTING_ERROR,
		MQ_CONSUME_ERROR,
	}

	for _, e := range allEnums {
		assert.NotEmpty(t, e.Message(), "错误码 %d 的消息不应为空", e.Code())
	}
}

func TestBizCodeEnum_CountByCategory(t *testing.T) {
	// 验证各分类错误码数量
	assert.Equal(t, 2, countEnums(COMMON_REPEAT_OPERATION, COMMON_NETWORK_ERROR), "Common 应有 2 个")
	assert.Equal(t, 4, countEnums(GROUP_REPEAT, GROUP_NOT_EXIST, GROUP_ADD_FAIL, GROUP_OPERATE_FAIL), "Group 应有 4 个")
	assert.Equal(t, 4, countEnums(CODE_GENERATE_ERROR, CODE_LIMITED, CODE_ERROR, CAPTCHA_ERROR), "Verification 应有 4 个")
	assert.Equal(t, 5, countEnums(ACCOUNT_REPEAT, ACCOUNT_NOT_EXIST, ACCOUNT_PWD_ERROR, ACCOUNT_UNLOGIN, ACCOUNT_TOKEN_ERROR), "Account 应有 5 个")
	assert.Equal(t, 7, countEnums(ORDER_PRICE_FAIL, ORDER_REPEAT_SUBMIT, ORDER_TOKEN_MISSING, ORDER_NOT_EXIST, ORDER_STATE_ERROR, ORDER_CANCEL_SUCCESS, ORDER_CONFIRM_SUCCESS), "Order 应有 7 个")
	assert.Equal(t, 4, countEnums(PAY_ORDER_FAIL, PAY_CALLBACK_SIGN_FAIL, PAY_ORDER_STATE_ERROR, PAY_ORDER_TIMEOUT_ERROR), "Payment 应有 4 个")
	assert.Equal(t, 3, countEnums(TRAFFIC_NOT_EXIST, TRAFFIC_REDUCE_FAIL, TRAFFIC_DATA_ERROR), "Traffic 应有 3 个")
}

func countEnums(enums ...BizCodeEnum) int {
	return len(enums)
}
